const { Pool } = require("pg");

var tables = `CREATE TABLE lists (
	listingkey int8 NULL,
	listingagentname text NULL,
	colistingagentname text NULL,
	listofficekey int8 NULL,
	availabilitydate int8 NULL,
	propertysubtype text NULL,
	documentsavailable json NULL,
	leaseamount float8 NULL,
	leaseamountfrequency int8 NULL,
	businesstype json NULL,
	waterbodyname int8 NULL,
	"view" json NULL,
	numberofbuildings int8 NULL,
	numberofunitstotal int8 NULL,
	lotfeatures json NULL,
	lotsizearea float8 NULL,
	lotsizedimensions text NULL,
	lotsizeunits text NULL,
	poolfeatures json NULL,
	roadsurfacetype json NULL,
	currentuse json NULL,
	possibleuse json NULL,
	anchorscotenants int8 NULL,
	waterfrontfeatures json NULL,
	communityfeatures json NULL,
	appliances json NULL,
	otherequipment json NULL,
	securityfeatures json NULL,
	totalactualrent float8 NULL,
	existingleasetype json NULL,
	associationfee float8 NULL,
	associationfeefrequency text NULL,
	associationname text NULL,
	associationfeeincludes json NULL,
	originalentrytimestamp text NULL,
	modificationtimestamp text NULL,
	listingid int8 NULL,
	internetentirelistingdisplayyn bool NULL,
	standardstatus text NULL,
	statuschangetimestamp text NULL,
	publicremarks text NULL,
	listprice int8 NULL,
	inclusions int8 NULL,
	colistofficekey int8 NULL,
	colistagentkey int8 NULL,
	listagentkey int8 NULL,
	internetaddressdisplayyn bool NULL,
	listingurl text NULL,
	originatingsystemname text NULL,
	photoscount int8 NULL,
	photoschangetimestamp text NULL,
	unparsedaddress text NULL,
	postalcode text NULL,
	subdivisionname text NULL,
	stateorprovince text NULL,
	streetdirprefix text NULL,
	streetdirsuffix text NULL,
	streetname text NULL,
	streetnumber text NULL,
	streetsuffix text NULL,
	unitnumber text NULL,
	country text NULL,
	city text NULL,
	directions int8 NULL,
	latitude float8 NULL,
	longitude float8 NULL,
	cityregion text NULL,
	parkingtotal int8 NULL,
	yearbuilt int8 NULL,
	bathroomspartial int8 NULL,
	bathroomstotalinteger int8 NULL,
	bedroomstotal int8 NULL,
	buildingareatotal int8 NULL,
	buildingareaunits text NULL,
	buildingfeatures json NULL,
	abovegradefinishedarea int8 NULL,
	abovegradefinishedareaunits int8 NULL,
	livingarea int8 NULL,
	livingareaunits text NULL,
	fireplacestotal int8 NULL,
	fireplaceyn bool NULL,
	fireplacefeatures json NULL,
	architecturalstyle json NULL,
	heating json NULL,
	foundationdetails json NULL,
	basement json NULL,
	exteriorfeatures json NULL,
	flooring json NULL,
	parkingfeatures json NULL,
	cooling json NULL,
	propertycondition json NULL,
	roof json NULL,
	constructionmaterials json NULL,
	stories int8 NULL,
	propertyattachedyn bool NULL,
	zoning int8 NULL,
	zoningdescription int8 NULL,
	taxannualamount float8 NULL,
	taxblock int8 NULL,
	taxlot int8 NULL,
	taxyear int8 NULL,
	structuretype json NULL,
	utilities json NULL,
	irrigationsource json NULL,
	watersource json NULL,
	sewer json NULL,
	electric json NULL,
	commoninterest text NULL,
	media json NULL,
	rooms json NULL,
	isdeleted int8 NULL,
	createdat text NULL
); 
  CREATE TABLE destinations (
	destinationid int8 NULL,
	destinationname text NULL,
	destinationurl text NULL,
	destinationtype text NULL,
	destinationstatus text NULL,
	memberfirstname text NULL,
	memberlastname text NULL,
	memberkey int8 NULL,
	originalentrytimestamp text NULL,
	modificationtimestamp text NULL,
	"isDeleted" text NULL,
	"listingagentname " text NULL,
	colistingagentname text NULL
);
  CREATE TABLE listingagentids (
      listingagentkeys int4,
      agentname text, 
      createdat text 
    );`;
(() => {
  const pool = new Pool({
    user: "bilalogist",
    host: "db.bit.io",
    database: "bilalogist/testdb",
    password: "v2_3zrcd_tHTWdTCZ3HJFkhCYRmz7yCY",
    port: 5432,
    ssl: true,
  });

  pool.query(tables, (err, res) => {
    pool.end();
    if (err) console.log(err);
    else console.log(res);
    // console.log(res.rows);
  });
})();
